MovieApp/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MovieApp/Models/Movie.cs
namespace MovieApp.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
    }
}

MovieApp/Models/MovieCategoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Models
{
    public class MovieCategoryModel
    {
        public Movie Movie { get; set; }
        public IEnumerable<Movie> Movies { get; set; }
        public IEnumerable<Category> Categories { get; set; }
    }
}

MovieApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;
using MovieApp.Models;
using System.Linq;

namespace MovieApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(int? id)
        {
            var movies = MovieRepository.Movies;
            if (id!=null)
            {
                movies = movies.Where(i => i.CategoryId == id).ToList();
            }
            return View(movies);
        }
        public IActionResult Details(int id)
        {
            return View(MovieRepository.GetById(id));
        }
        public IActionResult Contact()
        {
            return View();
        }
    }
}

MovieApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Controllers
{
    public class MovieController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        public IActionResult List()
        {
            return View();
        }
        public IActionResult Details()
        {
            return View();
        }

    }
}

MovieApp/ViewComponents/CategoryMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MovieApp.Data;

namespace MovieApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            if (RouteData.Values["action"].ToString()=="Index")
                ViewBag.SelectedCategory = RouteData?.Values["id"];
            return View(CategoryRepository.Categories);
        }

    }
}

MovieApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<h1>Home/Contact</h1>

MovieApp/Views/Home/Details.cshtml
@model Movie

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        <div class="card mb-3">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-4">
                       <img src="/img/@Model.ImageUrl" alt="@Model.Name" class="card-img" />
                    </div>
                    <div class="col-md-8">

                        <h5 class="card-title">@Model.Name</h5>
                        <p class="card-text lead">@Model.ShortDescription</p>
                        <p class="card-text">@Html.Raw(Model.Description)</p>
                        <p class="card-text">
                            <small class="text-muted">3 days ago</small>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MovieApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model IEnumerable<Movie>

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoryMenu")
    </div>
    <div class="col-md-9">
        @await Html.PartialAsync("_movies", Model)
    </div>
</div>

MovieApp/Views/Home/_movies.cshtml
@model IEnumerable<Movie>

@foreach (var movie in Model)
{
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-3">
                <a href="/Home/Details/@movie.Id"><img src="/img/@movie.ImageUrl" alt="@movie.Name" class="card-img" /></a>
            </div>
            <div class="col-md-9">
                <div class="card-body">
                    <h5 class="card-title"><a href="/Home/Details/@movie.Id">@movie.Name</a></h5>
                    <p class="card-text">@movie.ShortDescription</p>
                    <p class="card-text">
                        <small class="text-muted">3 days ago</small>
                    </p>
                </div>
            </div>
        </div>
    </div>
}

MovieApp/Views/Movie/Details.cshtml
@{
    ViewData["Title"] = "Movie";
}

<h1>Movie/Details</h1>

MovieApp/Views/Movie/Index.cshtml
@{
    ViewData["Title"] = "Movie";
}

<h1>Movie/Index</h1>

MovieApp/Views/Movie/List.cshtml
@{
    ViewData["Title"] = "Movie";
}

<h1>Movie/List</h1>

MovieApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<Category>

<a href="/" class="list-group-item list-group-item-action">Tüm Kategoriler</a>

<div class="list-group">
    @foreach (var item in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-id="@item.Id" class="list-group-item list-group-item-action @(ViewBag.SelectedCategory==item.Id.ToString()?" active":"")">@item.Name</a>
    }
</div>

MovieApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary box-shadow mb-3 py-4">
            <div class="container">
                <a href="/" class="navbar-brand"><img src="/img/logo.png" style="height:30px;width:auto;"></a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a href="/login" class="nav-link text-white">Login</a>
                    </li>
                    <li class="nav-item">
                        <a href="/register" class="nav-link text-white">Register</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top py-2 mt-3 footer text-muted bg-primary">
        <div class="container text-white">
            &copy; 2021 - MovieApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieApp/Views/Shared/_menu.cshtml
@model MovieCategoryModel

<div class="list-group">
    @foreach (var item in Model.Categories)
    {
        <a href="/Home/Index/@item.Id" class="list-group-item list-group-item-action">@item.Name</a>
    }
</div>